"""initial

Revision ID: 7118cfa46a77
Revises: 
Create Date: 2025-04-05 09:48:48.845464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7118cfa46a77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitude', sa.Text(), nullable=True))
        batch_op.alter_column('latitude',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=True)
        batch_op.drop_column('longtitude')

    with op.batch_alter_table('penerima_donasi', schema=None) as batch_op:
        batch_op.alter_column('id_penerima',
               existing_type=mysql.CHAR(length=3),
               type_=sa.String(length=3),
               existing_nullable=False)
        batch_op.alter_column('kontak',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=13),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('deskripsi',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('alamat',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('longtitude',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penerima_donasi', schema=None) as batch_op:
        batch_op.alter_column('longtitude',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('alamat',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('deskripsi',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('kontak',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=13),
               nullable=True)
        batch_op.alter_column('id_penerima',
               existing_type=sa.String(length=3),
               type_=mysql.CHAR(length=3),
               existing_nullable=False)

    with op.batch_alter_table('donasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longtitude', mysql.VARCHAR(length=255), nullable=False))
        batch_op.alter_column('latitude',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('longitude')

    # ### end Alembic commands ###
